<?php

namespace Epavia\EpaviaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeAbonnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAbonnementRepository extends EntityRepository
{
}
