<?php

namespace Entreprise\EntrepriseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CertificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificationRepository extends EntityRepository
{
}
